name: "Build and push images"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build images"
      env:
        REGISTRY: ghcr.io
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.actor }}/${{ github.repository }}:latest

      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Github
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.GH_TOKEN }}

      - name: Build and push images to Docker hub
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.GITHUB_REPOSITORY }}
